Proyectofinal/Controllers/BackofficeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyectofinal.Models;

namespace Proyectofinal.Controllers
{
    public class BackofficeController : Controller
    {
        // GET: Backoffice
        public ActionResult index()
        {
            if (Session["id"] != null)
            {
                string i = Session["id"].ToString();
                int id = Int32.Parse(i);
                Usuarios usu = BD.TraerUsuario(id);
                if (usu.IdUsuario != -1 && usu.Admin == true)
                {
                    Session["id"] = usu.IdUsuario;
                    Session["Admin"] = "true";
                    return View("Home");
                }
                return View();
            }                   
            else
            {
                return View();
            }
        }
        public ActionResult ValidarLoginAdmin(Login log)
        {
            if (ModelState.IsValid)
            {
                Usuarios usu = BD.ValidarLoginUsuario(log.Username, log.Contrasena);
                if (usu.IdUsuario != -1 && usu.Admin == true)
                {                
                    Session["id"] = usu.IdUsuario;
                    Session["Admin"] = "true";
                    return View("Home");
                }
                else
                {
                    return View("index");
                }
            }else
            {
                return View("index");
            }
        }

        public ActionResult Aprobar()
        {
            ViewBag.lista = BD.TraerResumenesSinAprobar();
            return View("");
        }
        public ActionResult VerDenuncias()
        {
            if (Login())
            {
                List<Denuncia> listaDenuncias = new List<Denuncia>();
                listaDenuncias = BD.TraerDenuncias();
                ViewBag.lista = listaDenuncias;
                return View("");
            }
            else
            {
                return RedirectToAction("index");
            }

        }

        public ActionResult Resumen (int id)
        {
            if (Login())
            {
            
            Denuncia d = BD.TraerDenunciaEspe(id);
            ViewBag.id = d.FkResumen;
            ViewBag.idDenu = id;
            return View("");
            }
            else
            {
                return RedirectToAction("index");
            }
        }

        public ActionResult Descartar(int id)
        {
            if (Login())
            {
                BD.BorrarDenuncia(id);
                return RedirectToAction("VerDenuncias");
            }
            else
            {
                return RedirectToAction("index");
            }
            
        }
        public ActionResult EliminarResumenXDenuncia(int id)
        {
            if (Login())
            {
            Denuncia d = BD.TraerDenunciaEspe(id);
            BD.EliminarResumen(d.FkResumen);
            BD.BorrarDenuncia(id);
            return RedirectToAction("VerDenuncias");
            }
            else
            {
                return RedirectToAction("index");
            }
        }

        public ActionResult MiResumen(int id)
        {
            Resumenes res = BD.TraerResumen(id);
            ViewBag.Nombre=res.Nombre;
            ViewBag.Descripcion = res.Descripcion;
            ViewBag.id = id;
            return View();
        }
        public ActionResult Resum(int id)
        {
            Resumenes res = BD.TraerResumen(id);
            ViewBag.Nombre = res.Nombre;
            ViewBag.Descripcion = res.Descripcion;
            ViewBag.id = id;
            return View();
        }

        public ActionResult AprobarResumen (int id)
        {
            if (Login())
            {
                BD.AprobarResumen(id);
            ViewBag.lista = BD.TraerResumenesSinAprobar();
            return View("Aprobar");
        }
            else
            {
                return RedirectToAction("index");
            }
        }
        public ActionResult RechazarResumen(int id)
        {
            BD.EliminarResumen(id);
            ViewBag.lista = BD.TraerResumenesSinAprobar();
            return View("Aprobar");
        }
        public ActionResult Datos()
        {
            if (Login())
            {
               
                ViewBag.lista = BD.TraerCantidadResumenesAprobados();
                ViewBag.lib = BD.TraerCantidadLibrosAprobados();
                ViewBag.libsin = BD.TraerCantidadLibrosSinAprobar();
                ViewBag.ressin = BD.TraerCantidadResumenesSinAprobar();
                ViewBag.usu = BD.TraerCantidadUsuarios();
                ViewBag.vend = BD.TraerCantidadResumenesLibrosVend();
                return View("");
            }
            else
            {
                return RedirectToAction("index");
            }
        }

        public ActionResult InsertarMateria()
        {
            if (Login())
            {
                return View();
            }
            else
            {
                return RedirectToAction("index");
            }
        }
        public ActionResult DespuesDeInsertarMateria(BuscadorLibros b)
        {
            if (Login())
            {

                BD.InsertarMateria(b.Busueda);
                return RedirectToAction("index");
            }
            else
            {
                return RedirectToAction("index");
            }
        }
        public ActionResult InsertarEscuela()
        {
            if (Login())
            {
                return View();
            }
            else
            {
                return RedirectToAction("index");
            }
        }
        public ActionResult DespuesDeInsertarEscuela(BuscadorLibros b)
        {
           
            if (Login())
            {
                BD.InsertarEscuela(b.Busueda);
                return RedirectToAction("index");
            }
            else
            {
                return RedirectToAction("index");
            }
        }
        public ActionResult BorrarMateria()
        {
            if (Login())
            {
                return View();
            }
            else
            {
                return RedirectToAction("index");
            }
        }
        public ActionResult BorrarEsta(int id)
        {
            if (Login())
            {
                BD.BorrarMateria(id);
                return RedirectToAction("BorrarMateria");
            }
            else
            {
                return RedirectToAction("index");
            }

        }

        public ActionResult BorrarEscuela()
        {
            if (Login())
            {
                return View();
            }
            else
            {
                return RedirectToAction("index");
            }
        }
        public ActionResult BorrarLaOtra(int id)
        {
            
            if (Login())
            {
                BD.BorrarEscuela(id);
                return RedirectToAction("BorrarEscuela");
            }
            else
            {
                return RedirectToAction("index");
            }
        }
        public ActionResult BorrarResumen()
        {

            if (Login())
            {
               
                return View();
            }
            else
            {
                return RedirectToAction("index");
            }
        }
        public ActionResult BorrarR(int id)
        {

            if (Login())
            {
                BD.EliminarResumen(id);
                return RedirectToAction("BorrarResumen");
            }
            else
            {
                return RedirectToAction("index");
            }
        }

        public ActionResult BorrarLibros()
        {

            if (Login())
            {

                return View();
            }
            else
            {
                return RedirectToAction("index");
            }
        }
        public ActionResult BorrarL(int id)
        {

            if (Login())
            {
                BD.EliminarLibro(id);
                return RedirectToAction("BorrarLibros");
            }
            else
            {
                return RedirectToAction("index");
            }
        }
        public bool Login()
        {
            bool l;
            if (Session["id"] != null && Session["Admin"] != null)
            {
                l = true;
            }
            else
            {
                l = false;
            }
            return l;
        }
        public ActionResult AprobarL()
        {
            if (Login())
            {
                ViewBag.lista = BD.TraerLibrosSinAprobar();
                return View();
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        public ActionResult AprobarLibros(int id)
        {
            if (Login())
            {
                BD.AprobarLibro(id);
                ViewBag.lista = BD.TraerLibrosSinAprobar();
                return View("AprobarL");
            }
            else
            {
                return RedirectToAction("index");
            }
        }
        public ActionResult MiLibros (int id)
        {
            ViewBag.id = id;
            return View("MisLibros");
        }
        public ActionResult RechazarLibro(int id)
        {
            BD.EliminarLibro(id);
            ViewBag.lista = BD.TraerLibrosSinAprobar();
            return View("AprobarL");
        }
        public ActionResult AgregarMP(int id)
        {
            ViewBag.id = id;
            ViewBag.ListaMaterias = BD.TraerMateria();
            ViewBag.ListaAños = BD.TraerAños();
            ViewBag.ListaEscuelas = BD.TraerEscuelas();
            return View("");
        }
        [HttpPost]

Proyectofinal/Views/Backoffice/Aprobar.cshtml
@using Proyectofinal.Models
@{
    ViewBag.Title = "Aprobar";
}
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css">
    <title>Resumamos</title>
</head>
<body>
    <div class="container">
        <!-- Header -->
        <!-- Hero Section -->

        <br />
        <br />
      



        <!-- Stats Gallery Section -->
        <div class="content content-shadow1">
            <div class="size_mother">

                <h3 class="Titulo"><b>Resumenes sin aprobar</b></h3>
                <div class="col1 pt-2 clear" style=" border-bottom:#d2d2d2 1px solid; padding-bottom:40px; ">
                    <div class="col1_2 fl l-2 clear">
                        <div class="container-">
                            <div class="row">

                                @foreach (Resumenes res in ViewBag.lista)
                                {


                                    <div class="col-lg-4 col-xs-6">
                                        <div class="card" style="box-shadow: 0 2px 10px -2px black;">
                                            <div class="card-body">
                                                <h4 class="card-title alert-info">@res.Nombre</h4>
                                                <p class="card-text">@BD.TraerMateriaxId(res.FkMateria).NombreMateria</p>
                                                <p class="card-text">@BD.TraerEscuelaxId(res.FkEscuela).NombreEscuela</p>
                                                <p class="card-text">Puntuacion: @res.Puntuacion</p>
                                                <p class="card-text"> Autor: @BD.TraerAutorResumen(res.IdResumen).Nombre @BD.TraerAutorResumen(res.IdResumen).Apellido</p>
                                                <p class="card-text">Puntuacion autor: @BD.TraerAutorResumen(res.IdResumen).Puntuacion</p>
                                                <div class="verMas">
                                                    <a href="@Url.Action("MiResumen", "Backoffice", new { id = res.IdResumen })" class="btn-lg btn-outline-primary"><b>Ver resumen</b></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                }

                            </div>
                            <center>
                                <div class="row">
                                    <div class="col-lg-6 col-xs-6">
                                        <a href="@Url.Action("AprobarTodos","Backoffice")" class="btn btn-lg btn-primary">Aprobar todos</a>
                                    </div>
                                    <div class="col-lg-6 col-xs-6">
                                        <a href="@Url.Action("RechazarTodosLosResumenes","Backoffice")" class="btn btn-lg btn-danger">Rechazar todos</a>
                                    </div>
                                </div>
                            </center>
                        </div>



                    </div>

                </div>
            </div>

        </div>







        <br />
        <center>
            <a type="Button" class="btn btn-primary" href="@Url.Action("index", "Backoffice")">Volver a la home <i class="fas fa-home"></i></a>
        </center>
        <br />
        <br />

        
    </div>


    <!-- Footer Section -->
    <!-- Copyrights Section -->
    <!-- Main Container Ends -->
</body>
</html>

Proyectofinal/Views/Backoffice/AprobarL.cshtml
@using Proyectofinal.Models
@{
    ViewBag.Title = "Aprobar";
}
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css">
    <title>Resumamos</title>
</head>
<body>
    <div class="container">
        <!-- Header -->
        <!-- Hero Section -->

        <br />
        <br />




        <!-- Stats Gallery Section -->
        <div class="content content-shadow1">
            <div class="size_mother">

                <h3 class="Titulo"><b>Libros sin aprobar</b></h3>
                <div class="col1 pt-2 clear" style=" border-bottom:#d2d2d2 1px solid; padding-bottom:40px; ">
                    <div class="col1_2 fl l-2 clear">
                        <div class="container-">
                            <div class="row">

                                @foreach (Libro li in ViewBag.lista)
                                {

                                    <div class="col-lg-6 col-xs-12">
                                        <div class="card" style="box-shadow: 0 2px 10px -2px black;">
                                            <a href="@Url.Action("MiLibros", "Backoffice", new { Id = li.IdLibro })">

                                                <div class="card-body">
                                                    <div class="container">
                                                        <div class="row">
                                                            <div class="col-4">
                                                                <img src="~/Content/Archivos/@li.NombreImagen" height="60px" width="60px" alt="...">
                                                            </div>
                                                            <div class="col-8">
                                                                <center>
                                                                    <h5 class="card-title">@li.Nombre</h5>
                                                                    <p class="card-text">Precio: $@li.Precio</p>

                                                                </center>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </a>
                                            <div class="container">
                                                <div class="row">
                                                    <div class="col-lg-12 col-xs-12">
                                                        <center>
                                                            <a href="@Url.Action("AgregarMP","Backoffice", new { Id = li.IdLibro })" class="btn btn-outline-success btn-block" role="button">Agregar link <i class="fas fa-thumbs-up"></i></a>
                                                        </center>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>


                                    </div>


                                }

                            </div>
                            <center>
                                <div class="row">
                                    <div class="col-lg-6 col-xs-6">
                                        <a href="@Url.Action("AprobarTodosLibros","Backoffice")" class="btn btn-lg btn-primary">Aprobar todos</a>
                                    </div>
                                    <div class="col-lg-6 col-xs-6">
                                        <a href="@Url.Action("RechazarTodosLosLibros","Backoffice")" class="btn btn-lg btn-danger">Rechazar todos</a>
                                    </div>
                                </div>
                            </center>
                        </div>


                    </div>

                </div>
            </div>

        </div>







        <br />
        <center>
            <a type="Button" class="btn btn-primary" href="@Url.Action("index", "Backoffice")">Volver a la home <i class="fas fa-home"></i></a>
        </center>
        <br />
        <br />


    </div>


    <!-- Footer Section -->
    <!-- Copyrights Section -->
    <!-- Main Container Ends -->
</body>
</html>

Proyectofinal/Views/Backoffice/BorrarEscuela.cshtml
@using Proyectofinal.Models;
@model Materia
@{
    ViewBag.Title = "Borrar escuela";
    List<Escuela> Lista = BD.TraerEscuelas();

}
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css">
    <title>Resumamos</title>
</head>
<body>
    <br />
    <br />
   
    <div class="container">
        <h3 style="text-align:center;"><b>Eliminar materias</b></h3>
        <div class="row">


            <table class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Nombre Escuela</th>
                        <th scope="col">Eliminar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Escuela m in Lista)
                    {
                        <tr>
                            <th>@m.NombreEscuela</th>
                            <td>
                                <a type="Button" class="btn btn-danger btn-sm" href="@Url.Action("BorrarLaOtra", "Backoffice", new { id = m.IdEscuela })">Eliminar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
    <br />
    <center>
        <a type="Button" class="btn btn-primary" href="@Url.Action("index", "Backoffice")">Volver a la home <i class="fas fa-home"></i></a>
    </center>
    <br />
    <br />
</body>
</html>

Proyectofinal/Views/Backoffice/BorrarLibros.cshtml
@using Proyectofinal.Models;
@model Libro
@{
    ViewBag.Title = "Borrar libros";
    List<Libro> Lista = BD.TraerLibros();

}
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css">
    <title>Resumamos</title>
</head>
<body>
    <br />
    <br />
    
    <div class="container">
        <h3 style="text-align:center;"><b>Eliminar libros</b></h3>
        <div class="row">


            <table class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Nombre Libro</th>
                        <th scope="col">Eliminar</th>
                        <th scope="col">Agregar MP</th>
                        <th scope="col">Ver mas</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Libro l in Lista)
                    {
                    <tr>
                        <th>@l.Nombre</th>
                        <td>
                            <a type="Button" class="btn btn-danger btn-sm" href="@Url.Action("BorrarL", "Backoffice", new { id = l.IdLibro })">Eliminar</a>
                        </td>
                        <td>
                            <a type="Button" class="btn btn-primary btn-sm" href="@Url.Action("AgregarMP", "Backoffice", new { id =l.IdLibro })">MP</a>
                        </td>
                        <td>
                            <a type="Button" class="btn btn-primary btn-sm" href="@Url.Action("Lib", "Backoffice", new { id =l.IdLibro })">Ver</a>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
    <br />
    <center>
        <a type="Button" class="btn btn-primary" href="@Url.Action("index", "Backoffice")">Volver a la home <i class="fas fa-home"></i></a>
    </center>
    <br />
    <br />
</body>
</html>

Proyectofinal/Views/Backoffice/BorrarMateria.cshtml
@using Proyectofinal.Models;
@model Materia
@{
    ViewBag.Title = "Borrar materias";
    List<Materia> Lista = BD.TraerMateria();

}
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css">
    <title>Resumamos</title>
</head>
    <body>
        <br />
        <br />
        
        <div class="container">
            <h3 style="text-align:center;"><b>Eliminar materias</b></h3>
            <div class="row">


                <table class="table table-striped">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">Nombre materia</th>
                            <th scope="col">Eliminar</th>
                            <th scope="col">Nombre materia</th>
                            <th scope="col">Eliminar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Lista.Count; i += 2)
                        {
                            <tr>
                                <th>@Lista[i].NombreMateria</th>
                                <td>
                                    <a type="Button" class="btn btn-danger btn-sm" href="@Url.Action("BorrarEsta", "Backoffice", new { id = Lista[i].IdMateria })">Eliminar</a>
                                </td>

                                @if (i + 1 < Lista.Count)
                                {

                                <th>@Lista[i + 1].NombreMateria</th>
                                <td>
                                    <a type="Button" class="btn btn-danger btn-sm" href="@Url.Action("BorrarEsta", "Backoffice", new { id = Lista[i + 1].IdMateria })">Eliminar</a>
                                </td>

                                }
                                else
                                {
                            
                                <th>

                                </th>
                                <td>
                                </td>
                            
                            }
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
        </div>
        <br />
        <center>
            <a type="Button" class="btn btn-primary" href="@Url.Action("index", "Backoffice")">Volver a la home <i class="fas fa-home"></i></a>
        </center>
        <br />
        <br />
    </body>
</html>

Proyectofinal/Views/Backoffice/BorrarResumen.cshtml
@using Proyectofinal.Models;
@model Resumenes
@{
    ViewBag.Title = "Borrar resumen";
    List<Resumenes> Lista = BD.TraerResum();

}
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css">
    <title>Resumamos</title>
</head>
<body>
    <br />
    <br />

    <div class="container">
        <h3 style="text-align:center;"><b>Eliminar resumenes</b></h3>
        <div class="row">


            <table class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Nombre Resumen</th>
                        <th scope="col">Eliminar</th>
                        <th scope="col">Ver mas</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Resumenes r in Lista)
                    {
                    <tr>
                        <th>@r.Nombre</th>
                        <td>
                            <a type="Button" class="btn btn-danger btn-sm" href="@Url.Action("BorrarR", "Backoffice", new { id = r.IdResumen })">Eliminar</a>
                        </td>
                        <td>
                            <a type="Button" class="btn btn-primary btn-sm" href="@Url.Action("Resum", "Backoffice", new { id =r.IdResumen })">Ver</a>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
    <br />
    <center>
        <a type="Button" class="btn btn-primary" href="@Url.Action("index", "Backoffice")">Volver a la home <i class="fas fa-home"></i></a>
    </center>
    <br />
    <br />
</body>
</html>